### ISSUE TITLE
>60FPS only works with V-SYNC ON (MacOS) ; without: frames get dropped, rendered frames limited to 60FPS

### ISSUE THREAD

**Issue by Foul-Tarnished** [moonlight-stream/moonlight-qt#1242]
**Describe the bug**
If you disable v-sync and frame pacing and choose 120fps : 
Rendering frame will be at 60FPS (incoming and decoding frames are still 120FPS though)

Moonlight thinks there's 50% frame dropped by network (wrong)

**Steps to reproduce**
- Have a 120Hz monitor or virtual display driver on host
- Set Moonlight to 120FPS, fullscreen, disable v-sync and disable frame pacing.
- Launch an app/desktop and open menu for stats

then test with v-sync on and see the expected result (120fps decoding frames and not 60fps)

**Screenshots**

**Affected games**
All

**Moonlight settings (please complete the following information)**
Forced H265, HDR, fullscreen

**Client PC details**
 - OS: MacOS Sonoma
 - Moonlight Version: latest stable
 - GPU: Mac M3

**Server PC details**
 - OS: Win11 23H2
 - Sunshine latest stable
 - GPU: RTX 4090
 - GPU driver: latest

**Moonlight Logs (please attach)**

**Comment by cgutman** [comment]
Can you try the latest nightly build? It has a completely new Metal renderer.

https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/49560740/job/t0g4r8qyjxnlovm7/artifacts

**Comment by cgutman** [comment]
This should be fixed by the new Metal renderer in v6.0.0

**Comment by zacbre** [comment]
I'm still encountering this one with 6.0.1 on MacOS Sonoma 14.5... Enabling VSync allows the framerate to go up to 120hz, but if I leave it off, the render framerate is 60.61fps.

**Comment by WeebLabs** [comment]
I am also encountering this issue with 6.1.0 under MacOS Sequoia 15.0.
