### ISSUE TITLE
Mouse Responsiveness

### ISSUE THREAD

**Issue by Dalizzi** [moonlight-stream/moonlight-qt#125]
When using touchpad, performance for the mouse cusor is very good. After changing to a mouse and doing rapid hovering over the screen, there is very significant latency. I think client sends too much mouse events to the server etc.

**Comment by Dalizzi** [comment]
Ok, I'll try to help you with this tomorrow. Can't tell the versions currently but those are quite recent. 

Another issue come to my mind, you are using QRunnable to execute single process in multiple threads simultaneously in Win(x) environment. That was proven to be not a working interface to handle parallel processing couple of years back. Please print kernel thead ID:s, ( Qt thread ID should be logically same ), to see if those threads are actually different than main thread ID.

**Comment by Dalizzi** [comment]
Well, I can't say I have sources related to that, ( I can get you those ). Couple of years back it was a problem with like Qt 5.1 or similar to execute parallel threads in CPU through QT. QT Architecture overally doesn't harmonize any manipulation of a single object in several threads, like QObject. That is why there is a function in QOjbect, ,moveToThread. That is the paradigm, how objects are kind of dedicated for threads running inside application. Now, E.g. Java uses Runnable paradigm, to execute tasks under an interpreter, but that is overally synchronized by the programmer through mutexes (synchronize), and eventually synchronized in CPU level through the interpreter.
But In Qt, to support connections, you have to have a clear responsibility for the data. And this is why QRunnable didn't work at the first time, and I don't know does it work even now. 
Proper way to do parrallelism in Qt in a single process, is to create a QThread, then move objects related to the thread and execute.
Easily you can check  QThread::currentThreadId(), does it actually return different ID in each (thread). It is a static function.

**Comment by Dalizzi** [comment]
Can you give instructions how to capture exact logs ? It seems when rising bandwith, issue gets worse. Yet touchpad latency is realtime. Same thing with the 'shadow' process I'm struggling with, that is a very minor thing however. Also repeated that issue.

**Comment by Dalizzi** [comment]
About 'rapid hovering', means I rapdily move mouse cursor. Works fine with touchpad. With mouse it generates big overhead / latency on view.

**Comment by cgutman** [comment]
On Windows, `Moonlight-###.log files` can be found in `%TEMP%`. Simply type that into the File Explorer path field to navigate there. Collect the latest log after streaming and replicating the issue during your session.

**Comment by cgutman** [comment]
Your version of GeForce Experience and Moonlight are both out of update. Please update both and that should resolve the issue.

**Comment by Dalizzi** [comment]
Ok, thanks, I'll do that and report if issue is reproduced.

**Comment by Dalizzi** [comment]
Updated GF experience, driver and moonlight. Issue is still reproducible. Tried both 50Mb/s and 20Mb/s.
[lg.zip](https://github.com/moonlight-stream/moonlight-qt/files/2554554/lg.zip)

**Comment by cgutman** [comment]
GeForce Experience is still out of date:
```
00:00:04 - Qt Info: Server GPU: "GeForce GTX 970"
00:00:04 - Qt Info: Server GFE version: "3.13.1.30"
```

The current version of GFE is 3.15.0.186.

**Comment by Dalizzi** [comment]
Not reproduced with latest GFE.
