### ISSUE TITLE
Cant close connection sometimes, error 503

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#1279]
It happens often, that you cant close streams in Moonlight getting error 503 "all sessions must be disconnected before quitting".

There are no other connections, using just one client. Waiting also doesnt help.

1. open connection
2. put to sleep with ctrl alt shit q
3. click the stop button in moonlight
4. doesnt work

![image](https://github.com/moonlight-stream/moonlight-qt/assets/6721083/0c536809-4c5a-4d8c-b5cb-6aac35c284c7)

Client Windows 11 Moonlight windows 5.0.1, Windows 11 Sunshine latest stable.

This doesnt happen every single time but really often, not proper way to reproduce. Only way to fix is to restart Sunshine on host.

**Comment by cgutman** [comment]
Have you adjusted the Ping Timeout value on the Network tab of Sunshine from the default value of 10000?

Does the error still persist if you fully exit Moonlight, wait 10 seconds, then open Moonlight and try to connect again?

**Comment by makedir** [comment]
@cgutman Nope. Nothing changed. The issue happens all the time now and is super annoying. It happens randomly. Just happened again.

Started host via WOL. Wanted to connect with Moonlight 5.01 got the above error. Then it is bugged out and cant close the stream anymore in Moonlight. Waiting doesnt fix this.

**Comment by makedir** [comment]
And again just happened with Moonlight 6.0.0

![image](https://github.com/moonlight-stream/moonlight-qt/assets/6721083/e1d83d76-382d-469d-a7f6-88eef1701b25)

**Comment by cgutman** [comment]
Screenshots of the error dialog aren't enough for detailed troubleshooting. Please attach the logs from both Moonlight (located in the Temp folder) and Sunshine (configured for Debug-level verbosity) after experiencing the issue.

**Comment by makedir** [comment]
Issue still not fixed in 6.0.1

![image](https://github.com/moonlight-stream/moonlight-qt/assets/6721083/f6ae13b6-9f5b-45b9-ab42-31e3c02f5907)

**Comment by misaka00251** [comment]
I'm having the same issue, Using latest moonlight & sunshine version.

**Comment by makedir** [comment]
Of course. This issue exists since ages.

**Comment by dcuellar** [comment]
Same here. It's weird. I have other applications and the issue doesn't happen with those. Actually, it does happen when I exit using the hotkey combination. If I exit the app (let's say BigBox) then the stream ends normally. Since the desktop isn't executing an app the only way to quit it would be if I use the hotkey combination.

Hope that makes sense.

**Comment by dcuellar** [comment]
Ok. For those of you who are experiencing this issue... quick question for ya. 

Are you using Sunshine or GFE?

Sunshine:
Did you by chance change the image to the desktop application in sunshine? I found that if you changed the path to a different image, in other words... have anything other than "desktop.png" in this field then this error occurs. I reverted to "desktop.png" and it started to work no problem. The solution to getting a different image would be to replace the existing file with another and be sure to name it "desktop.png". 

GFE:
In Gameforce the desktop app has to have an application path to the mstsc.exe file. Usually found in C:\Windows\System32\mstsc.exe. I'm not using GFE but this is what I read around as a solution to this issue for those folks.

Let me know how it goes.

**Comment by makedir** [comment]
Sunshine of course. What you mean with desktop application and image? No I did not change any images, but I changed settings to desktop so it would execute things, maybe that also causes the issue. Sunshine also randomly seems to still be running and the pause icon is in the systray even I closed the connection.

**Comment by dcuellar** [comment]
When I looked at the documentation for sunshine it says that in order to create a desktop application you have to fill in two things. Name it “Desktop” and put “desktop.png” for the image. It doesn’t specifically say you HAVE to leave all other cells blank but it does say to leave them blank. 

Try removing it all except those two fields. See if that works.

You could also try adding a command to a program and then just minimize it until you are ready to exit. Some people mentioned using cmd as the program.

**Comment by makedir** [comment]
Again. I have not changed anything on that matter or added any applications, as you see on the above screenshots, it is the default Desktop with no image at all.

**Comment by dcuellar** [comment]
What did you mean by…
“but I changed settings to desktop so it would execute things, maybe that also causes the issue.”

My response was because I thought you meant that you added something else to this application on another field.

If you didn’t…and all you have are the Name and image fields filled in then I do not know what else to recommend other than what I recommended about using an app in the command field like cmd.

**Comment by dcuellar** [comment]
Also, let me make this clear in case it isn’t already evident. I’m not responsible for any of these apps. I am just a random person who had the same issue and is trying to help because I was able to solve it on my end. 

I hope you figure it out.

**Comment by Orangestar12** [comment]
If I can bring this back and make a suggestion to be more conducive, Moonlight should include an option to "kick" other sessions out so you can reconnect in the event of a dropped connection or unknowingly leaving another computer connected. (Theoretically, Sunshine would have to come to an agreement on how to implement this.) It would be more secure than asking users to decrease the ping timeout or increase the number of allowed connections.

**Comment by makedir** [comment]
Of course. I have zero idea why this is not implemented or the default behavior.

**Comment by MRMY000** [comment]
I've encountered the same issue in version 6.1.0.0. 
I didn't change the Ping Timeout value, and I quit moonlight, closed vpn, and waited for even 10 min. That didn't work. 
When I restarted vpn and moonlight, reconnected with host machine successfully, and tried to close connection again, I still met 503.
I had never changed desktop picture. All I've changed: Display Device Specify, Advertised Resolutions, Language.

But I've found a way that might can close the Sessions.
**Try to restart Sunshine while connecting.** 
It's to say, use Moonlight to click the "restart" btn of Sunshine.
Then your Moonlight will quit, but you can try to connect again. You can connect successfully if nothing wrong, and then try to close connection in normal way, probably 503 won't occur.

Something must be awared of:
The work might not be saved successfully, because it's not the normal way.
Personal advice, don't close Sunshine completely, or reconnection might be unavailable.

I'm just a random person who had the same issue, but let me know if my way works.

**Comment by makedir** [comment]
..... obviously restarting Sunshine will fix it, thats not a solution if you dont have access to the pc. This needs to be fixed.

**Comment by makedir** [comment]
I have enough of this, latest Moonlight and Sunshine nightly, still not fixed

![image](https://github.com/user-attachments/assets/611b0c26-9020-44c3-b4b4-d70799d8aeb8)

**Comment by cgutman** [comment]
Let's keep each GitHub issue to a single topic.

The original report of error 503 is fixed by lifting the restriction that all sessions be disconnected in https://github.com/LizardByte/Sunshine/pull/3325, so that part is fixed in the latest pre-release Sunshine versions. I'm closing this bug as the original reported error has been addressed externally.

For the control stream error, please open a separate ticket _and attach logs_. Note: You _must_ complete the entire issue template, including providing logs.

**Comment by makedir** [comment]
Still not fixed:

Issue happened now again on 6.1.0

![image](https://github.com/user-attachments/assets/e631c927-fa81-4682-9024-580fb1dbfe9c)

**Comment by makedir** [comment]
Still not fixed with latest Sunshine connecting first times not working a few times

![Image](https://github.com/user-attachments/assets/87376657-deaa-4671-9f2f-b3155019f54f)

**Comment by camemb3rt** [comment]
Experiencing the same exact issue as @makedir. Running version 6.1.0
