### ISSUE TITLE
Constant flickering when starting a stream on Raspberry Pi 5 / Bookworm

### ISSUE THREAD

**Issue by theaioverlord** [moonlight-stream/moonlight-qt#1336]
**Describe the bug**
When I attempt to start streaming anything from my Sunshine server to my moonlight-qt client, the client screen continuously flickers between showing the moonlight-qt window, a black screen, and the stream. 

**Steps to reproduce**

1. Launch moonlight-qt from terminal
2. Select Sunshine server
3. Launch Steam Big Picture Mode or Desktop

**Screenshots**
Not able to provide screenshots.

**Affected games**
 - Steam Big Picture Mode
 - Desktop

**Other Moonlight clients**
The issue does not occur with other clients. Tested with Moonlight v6.0.0 on Steam Deck OLED

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults?
No

**Gamepad-related issues (please complete if problem is gamepad-related)**
N/A

**Client PC details (please complete the following information)**
 - OS: Raspberry Pi OS (Lite) Bookworm (64-bit)  
 - Moonlight Version:  v6.0.0
 - GPU: VideoCore VII (Raspberry Pi 5)
 - Linux package type (if applicable): apt (used Raspbian installation script from [moonlight-docs instructions](https://github.com/moonlight-stream/moonlight-docs/wiki/Install-Moonlight-Qt-on-Raspberry-Pi-4))

**Server PC details (please complete the following information)**
 - OS: Windows 10 22H2
 - Sunshine version: Sunshine v0.23.1
 - GPU: NVIDIA GeForce RTX 3080
 - GPU driver: 552.44

**Moonlight Logs (please attach)**
[moonlight_bug.txt](https://github.com/user-attachments/files/15945709/moonlight_bug.txt)
-Note: added comments to log file, indicated by "#" 

**Additional context**
- the stream recognizes inputs from my gamepad or keyboard while this issue is occurring, but it takes several attempts to successfully quit the stream using the keyboard/gamepad button shortcut.
- Based on the terminal output (attached) and the timing required to successfully quit the stream with the keyboard shortcut, it seems like moonlight-qt is continuously disconnecting and re-establishing the stream.
- changing the bitrate does not resolve the issue.

**Comment by Lexforce** [comment]
Exact same issue here. 
I can stream perfectly to my phone and other units, but not to moonlight-qt on my RP5.
I have the same everything (SW version wise, etc) as OP, except a RTX 3060 instead.

**Comment by mpendel** [comment]
Same issue-- RPI4, bookworm, Also tried bullseye. No difference.
RTX 2060 & Sunshine on host.
Setup works with moonlight on steamlink, and moonlight-embedded on retropie.

**Comment by cgutman** [comment]
I believe I fixed this in ec7137e693f8663db7afb4d92e86f69599e5127c and a0c77d0ad83b770e186340edbb29b278312a8e9c/ Please try this Bookworm build to verify: 
[moonlight-qt_6.0.0-1_arm64.deb.gz](https://github.com/user-attachments/files/15950143/moonlight-qt_6.0.0-1_arm64.deb.gz) 

(GitHub doesn't accept deb files, so you'll need to unzip it with `gzip -d moonlight-qt_6.0.0-1_arm64.deb.gz`  before you can use `dpkg -i` to install it).

**Comment by Lexforce** [comment]
> I believe I fixed this in [ec7137e](https://github.com/moonlight-stream/moonlight-qt/commit/ec7137e693f8663db7afb4d92e86f69599e5127c) and [a0c77d0](https://github.com/moonlight-stream/moonlight-qt/commit/a0c77d0ad83b770e186340edbb29b278312a8e9c). Please try this Bookworm package to verify: [moonlight-qt_6.0.0-1_arm64.deb.gz](https://github.com/user-attachments/files/15950143/moonlight-qt_6.0.0-1_arm64.deb.gz)
> 
> (GitHub doesn't accept deb files, so you'll need to unzip it with `gzip -d moonlight-qt_6.0.0-1_arm64.deb.gz` before you can use `dpkg -i` to install it).

Thank you for the quick response.
I can verify that everything works perfectly with those patches! :)
Great work, ship it! :D

**Comment by mpendel** [comment]
This worked for me too. Other problems still exist, but in the scope of this issue, its working on Rpi4 bookworm 64-bit Lite

**Comment by theaioverlord** [comment]
> I believe I fixed this in [ec7137e](https://github.com/moonlight-stream/moonlight-qt/commit/ec7137e693f8663db7afb4d92e86f69599e5127c) and [a0c77d0](https://github.com/moonlight-stream/moonlight-qt/commit/a0c77d0ad83b770e186340edbb29b278312a8e9c). Please try this Bookworm package to verify: [moonlight-qt_6.0.0-1_arm64.deb.gz](https://github.com/user-attachments/files/15950143/moonlight-qt_6.0.0-1_arm64.deb.gz)
> 
> (GitHub doesn't accept deb files, so you'll need to unzip it with `gzip -d moonlight-qt_6.0.0-1_arm64.deb.gz` before you can use `dpkg -i` to install it).

This worked! Thank you so much.

**Comment by ragebflame** [comment]
Getting the same issue here on Raspberry Pi 4, bullseye 11.9 aarch64.

Patched package failing to install with:

> (Reading database ... 51220 files and directories currently installed.)
> Preparing to unpack moonlight-qt_6.0.0-1_arm64.deb ...
> Unpacking moonlight-qt (6.0.0-1) over (6.0.0-1) ...
> dpkg: dependency problems prevent configuration of moonlight-qt:
>  moonlight-qt depends on libc6 (>= 2.35); however:
>   Version of libc6:arm64 on system is 2.31-13+rpt2+rpi1+deb11u10.
>  moonlight-qt depends on libssl3 (>= 3.0.0); however:
>   Package libssl3 is not installed.
>  moonlight-qt depends on libwayland-client0 (>= 1.20.0); however:
>   Version of libwayland-client0:arm64 on system is 1.18.0-2~exp1.1.
>  moonlight-qt depends on libdecor-0-0; however:
>   Package libdecor-0-0 is not installed.

I'll wait for the full 6.0.1 release and retest.
