### ISSUE TITLE
No audio on Crouton (chromebook linux chroot)

### ISSUE THREAD

**Issue by ppibburr** [moonlight-stream/moonlight-qt#146]
App works and performs well otherwise, however when connecting, a message stating audio device not found is displayed, and there is no audio

**Comment by cgutman** [comment]
Are you using the Flatpak?

**Comment by ppibburr** [comment]
Yes, following instructions found, https://flathub.org/apps/details/com.moonlight_stream.Moonlight, install from command line

**Comment by cgutman** [comment]
Audio doesn't seem to be supported in Crostini itself. Nor is hardware accelerated video decoding, which is likely to impact performance.

https://www.reddit.com/r/Crostini/comments/9l98d9/audacity_is_silent/
https://bugs.chromium.org/p/chromium/issues/detail?id=781398
https://chromium.googlesource.com/chromiumos/docs/+/master/containers_and_vms.md

I would recommend the ChromeOS Moonlight client for streaming on your Chromebook.

**Comment by ppibburr** [comment]
sure. here's a gist with all three items.  
https://gist.github.com/ppibburr/43717957fda00605c2e033640876115b

**Comment by cgutman** [comment]
There are a lot of errors attempting to talk to PulseAudio:
```
00:00:05 - SDL Info (0): Audio backend: ALSA
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused
00:00:05 - SDL Info (0): Selected audio device: Default ALSA Output (currently PulseAudio Sound Server)
00:00:05 - SDL Warn (0): No compatible channel layouts found. Some channels may not be played!
00:00:05 - SDL Info (0): Native layout: <UNKNOWN> (0 channels)
00:00:05 - SDL Error (0): soundio_outstream_open() failed: unable to open device
```

I suspect that it is one of these two issues:
https://github.com/flatpak/flatpak/issues/878
https://github.com/flatpak/flatpak/issues/1810

Can you try the solutions there?

**Comment by ppibburr** [comment]
flatpak update --commit=51c650457487f873129c0acee020fc61e25e54290e3126684e7734510652e8c3 com.moonlight_stream.Moonlightthat along with PULSE_SERVER=unix:/var/foo/bar flatpak run com.example.appenables (not solve) audio for #146prior to reverting the commit, audio error went away,but no sound, stream even showed up in mixer
--

**Comment by CrashyBang** [comment]
Hey @ppibburr where can I find the value for `/var/foo/bar` in the above example.

**Comment by cgutman** [comment]
Should be fixed by d1640e3bb8aca1de0417a73596ca9a6d0dae5205

**Comment by ppibburr** [comment]
does not fix. and not a A2DP issue.  

again,  
`flatpak update --commit=51c650457487f873129c0acee020fc61e25e54290e3126684e7734510652e8c3 com.moonlight_stream.Moonlight` allows it to have sound, and by far the best way to moonlight on chromebook

**Comment by cgutman** [comment]
Please retest with v0.8.1

**Comment by ppibburr** [comment]
sound is confirmed working, smidge of crackle to it., gets less crackly after a while of loading a stream

**Comment by ppibburr** [comment]
however, why must i repair every time i run moonlight?

**Comment by cgutman** [comment]
Interesting, maybe 25 ms buffer is still not enough for your device.

You shouldn't need to pair again unless you are switching between builds before v0.8.0 and builds after v0.8.0. The older build deletes some data used by the newer build for pairing security. Maybe that's happening for you? I haven't heard any other reports of that behavior.

**Comment by ppibburr** [comment]
i run via `flatpak run com.moonlight_stream.Moonlight` pair, exit, re-run and again i must pair.

**Comment by cgutman** [comment]
@ppibburr OK, please perform the following steps to get logs:

1. Pair your host PC with Moonlight, then close Moonlight.
1. Run `flatpak run --command="cat" com.moonlight_stream.Moonlight ~/.var/app/com.moonlight_stream.Moonlight/config/Moonlight\ Game\ Streaming\ Project/Moonlight.conf > paired.conf`
2. Run `flatpak run com.moonlight_stream.Moonlight &> unpaired.log` which should show your PC unpaired again per the bug. Don't pair again yet. Close Moonlight.
3. Run `flatpak run --command="cat" com.moonlight_stream.Moonlight ~/.var/app/com.moonlight_stream.Moonlight/config/Moonlight\ Game\ Streaming\ Project/Moonlight.conf > unpaired.conf`
4. Run `flatpak run com.moonlight_stream.Moonlight &> paired.log` and pair your PC again, then close Moonlight.
5. Email me the 4 files directly at cameron@moonlight-stream.org. You should not post them publicly because they have private keys in them.

**Comment by cgutman** [comment]
Quoting from email:
> I have it installed as system level, as i did before 8.0+,
 i ran as root after these files were made, and it maintained paired state, before 8.0+ however it worked fine as a system level install as a normal user

> as a followup, now only root may launch it, and it takes thrice the time to load

I agree. It looks like a Flatpak issue https://github.com/flatpak/flatpak/issues/2200 

That might explain why changes to your Moonlight.conf fail to save properly. I confirmed neither Moonlight.conf had the expected `srvcert` value required for pairing.
