### ISSUE TITLE
Flatpak hardware decoding not working (even after following the troubleshooting steps)

### ISSUE THREAD

**Issue by alterNERDtive** [moonlight-stream/moonlight-qt#1468]
**Describe the bug**
![image](https://github.com/user-attachments/assets/00e76b14-4448-43e6-a002-0d20fb2c593f)

I followed the troubleshooting instructions at https://github.com/moonlight-stream/moonlight-docs/wiki/Fixing-Hardware-Decoding-Problems, no dice.

Hardware acceleration is available and working in other applications. I also tested the Moonlight AppImage which is working fine _with_ hardware acceleration.

This reliably happens on my media center PC (initial occurrence, integrated AMD GPU), laptop (integrated AMD GPU) and main workstation (dedicated AMD GPU).

**Steps to reproduce**
1. have an AMP GPU
2. be on a Fedora 41 machine (might or might not be relevant)
3. install mesa, libva and libvdpau (`-freeworld`) from RPM Fusion
4. try running the Moonlight flatpak
5. observe it complain about missing hardware acceleration
6. install `org.freedesktop.Platform.GL.default//22.08-extra` from flathub according to https://github.com/moonlight-stream/moonlight-docs/wiki/Fixing-Hardware-Decoding-Problems#linux (tried both user and system installation)
7. do a `flatpak update` for good measure
8. try running the Moonlight flatpak
9. observe it _still_ complain about missing hardware acceleration

**Other Moonlight clients**
It appears to be specific to the flatpak installation as it works with the AppImage. I suspect the information on the troubleshooting page is outdated but I’m not well-versed enough in flatpak things to troubleshoot this properly myself.

**Moonlight settings (please complete the following information)**
I forced hardware acceleration for testing. I double checked flatseal, Moonlight has access to “all devices” (side note: wouldn’t it be possible to restrict that to specific things, like hardware acceleration?).

**Client PC details (please complete the following information)**
 - OS: Fedora 41
 - Moonlight Version: 6.1.0
 - GPU: whatever integrated GPU the AMD Ryzen 5 3550H comes with
 - Linux package type (if applicable): Flatpak

**Server PC details (please complete the following information)**
not relevant, but …
 - OS: Fedora 41
 - Sunshine or GeForce Experience version: Sunshine 0.23.1.8b21db6
 - GPU: AMD Radeon RX 7800 XT
 - GPU driver: mesa 24.2.7

**Moonlight Logs (please attach)**
[moonlight.log](https://github.com/user-attachments/files/17892717/moonlight.log)

**Additional context**
As I said, using the AppImage version fixes the acceleration problem … but it doesn’t support wayland, apparently:

```
00:00:00 - Qt Warning: Could not find the Qt platform plugin "wayland" in ""
00:00:00 - Qt Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```

Which means I’ll have to disable scaling manually every time I want to stream 4k with Moonlight :(

**Comment by jwangac** [comment]
If you're using a wlroots-based compositor like Sway, the issue might be related to the recent deprecation of wl_drm in wlroots. I encountered a similar problem, and the logs were quite similar to yours.

In my case, using Sway 1.10, enabling the debug flag "-Dlegacy-wl-drm" (when run sway) resolved the issue.

Additionally, the fix may require updating to libva 2.22.0, which supports the newer linux-dmabuf protocol.

**Comment by alterNERDtive** [comment]
> If you're using a wlroots-based compositor like Sway, the issue might be related to the recent deprecation of wl_drm in wlroots. I encountered a similar problem, and the logs were quite similar to yours.

I am indeed using Sway.

> In my case, using Sway 1.10, enabling the debug flag "-Dlegacy-wl-drm" (when run sway) resolved the issue.

I might try that, thanks. Currently happy with just using the AppImage, though.

**Comment by alterNERDtive** [comment]
> In my case, using Sway 1.10, enabling the debug flag "-Dlegacy-wl-drm" (when run sway) resolved the issue.

Just FYI, that does not work for me.

> Additionally, the fix may require updating to libva 2.22.0, which supports the newer linux-dmabuf protocol.

```bash
~> rpm -q libva
libva-2.22.0-3.fc41.x86_64
libva-2.22.0-3.fc41.i686
```

**Comment by cgutman** [comment]
I think this is because the KDE 6.7 runtime uses an older version of libva which breaks without `wl_drm`.

Please try the beta branch of the flatpak which uses the newer 6.8 runtime and let me know if that works.
```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo
flatpak install flathub-beta com.moonlight_stream.Moonlight
flatpak run com.moonlight_stream.Moonlight//beta
```

**Comment by alterNERDtive** [comment]
> I think this is because the KDE 6.7 runtime uses an older version of libva which breaks without `wl_drm`.

Ah yes, Flatpak …

> Please try the beta branch of the flatpak which uses the newer 6.8 runtime and let me know if that works.

It does. That is, with Sway’s debug flag. I’d assume without it it still won’t :)

**Comment by cgutman** [comment]
Can you provide a new log with the latest version of the stable Moonlight flatpak (not the beta one)?

**Comment by alterNERDtive** [comment]
I can’t test actual streaming right now, but at least I am not getting an error message when opening the application with forced hardware decoding.

**Comment by cgutman** [comment]
The update to use the 6.8 runtime change was merged to stable a long time ago, so this should be fixed.

**Comment by mikezila** [comment]
It is still not functioning on a fully up to date KDE. Other Flatpak applications such as mpv have functional hardware video decoding. I'm using an Intel GPU on Arch.

**Comment by UnsavedTrash** [comment]
I'm encountering the same issue with Nvidia, forcing it to run in xwayland gets the GUI to launch but it will only allow connections and decode video if I force software decoding. Otherwise it will lock up and crash. 

Operating System: Fedora Linux 43
KDE Plasma Version: 6.5.4
KDE Frameworks Version: 6.21.0
Qt Version: 6.10.1
Kernel Version: 6.17.12-300.fc43.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5700X 8-Core Processor
Memory: 64 GiB of RAM (62.7 GiB usable)
Graphics Processor: NVIDIA GeForce RTX 3090

**Comment by haxwithaxe** [comment]
I'm getting the same behavior with Debian 13, Sway 1.10.1, and integrated Intel graphics. AppImage (version 6.1.0) works fine. Flatpak (version 6.1.0) can't do hardware acceleration. I used flatseal to allow all access to hardware and filesystems as well as the troubleshooting guide steps.
