### ISSUE TITLE
macOS Tahoe Liquid Glass Window Borders

### ISSUE THREAD

**Issue by abedef** [moonlight-stream/moonlight-qt#1661]
**Describe the bug**
With the introduction of macOS's Liquid Glass design, some windows now have a thin border that changes based on surrounding colours. Previously, Moonlight's (borderless fullscreen) window would appear flush across the edge of the display, whereas now the display shows a thin line going all around.

**Steps to reproduce**
Install macOS 26.0 Beta (25A5316i) and launch a Moonlight stream in full screen (or borderless full screen). The edges of the screen are no longer flush – there is a border around it.

**Screenshots**
<img width="1024" height="1024" alt="Image" src="https://github.com/user-attachments/assets/c435acc4-0f7c-4593-b6b0-9009b55128ab" />

**Affected games**
This is a general streaming issue for macOS 26.0 clients.

**Other Moonlight clients**
This affects macOS 26.0 clients only.

**Moonlight settings (please complete the following information)**
Using default full screen behaviour as defined out-of-the-box for macOS clients.

**Client PC details (please complete the following information)**
 - OS: macOS 26.0 Beta (25A5316i)
 - Moonlight Version: 6.1.0
 - GPU: Apple M2 Max (64GB)

**Server PC details (please complete the following information)**
 - OS: Windows 11
 - Sunshine or GeForce Experience version: Sunshine v2025.122.141614
 - GPU: RTX 4090
 - GPU driver: 576.40

**Moonlight Logs (please attach)**
[Moonlight-1753847333.log](https://github.com/user-attachments/files/21500876/Moonlight-1753847333.log)

**Comment by BitGrub** [comment]
Have you found a workaround yet? On iPadOS 26 there's a similar issue, but toggling the fullscreen, or moving the window around a bit fixes the bug. Haven't made the jump to Tahoe yet, so I'm looking for issues in my most used programs first

**Comment by abedef** [comment]
Unfortunately not, but it seems the border effect may have become less pronounced over the last couple updates because it's been easy to tune out lately. Hard to say, since a window's borders seem to be affected by the colours surrounding it.

<img width="525" height="325" alt="Image" src="https://github.com/user-attachments/assets/81681a8f-e09a-4827-84f7-569ad5757d20" />

This screenshot is taken on macOS 26.0 Beta (25A5346a)

**Comment by cgutman** [comment]
I'm not seeing this behavior on macOS 26.0.1, so I'm going to assume it was a bug Apple fixed during the Tahoe beta period.

**Comment by abedef** [comment]
@cgutman I actually still see this border issue on the latest macOS – I can upload screenshots later tonight. This issue remains unresolved.

**Comment by cgutman** [comment]
Maybe I'm not understanding the issue? Here's a screenshot of a 1080p stream of a black desktop while switching between spaces using the trackpad on my M2 MBP, and I'm not seeing any gray line around the border of the Moonlight stream.

<img width="1800" height="1169" alt="Image" src="https://github.com/user-attachments/assets/dc57b396-d4b2-4610-83a6-cabec40252c1" />

**Comment by abedef** [comment]
Hmm could be something specific to my configuration then, I'll share more details along with my screenshot later. Thanks for looking into this.

**Comment by abedef** [comment]
The first thing that comes to mind – does your moonlight application run in full screen? Does it occupy its own space in your macOS screens? Do you access the moonlight screen by swiping with three fingers to the left?

**Comment by abedef** [comment]
Here is a screenshot I took on top of a larger black canvas – you can see the grey outline surrounding the entire screenshot. <img width="3556" height="2334" alt="Image" src="https://github.com/user-attachments/assets/f0335726-7732-41f8-af36-a309b677eaee" />

**Comment by abedef** [comment]
I took the above screenshot with "Borderless Windowed" mode enabled. When I switch it to "Fullscreen" it looks the same to me:

<img width="3556" height="2334" alt="Image" src="https://github.com/user-attachments/assets/bb922991-4568-4b1f-899f-5423b681a553" />

**Comment by abedef** [comment]
It could be that the effect is more noticeable on a dark background (especially noticeable during a game's loading screen) but I can't tell from your screenshot what the border looks like – it appears to be cut off?

**Comment by abedef** [comment]
<img width="636" height="395" alt="Image" src="https://github.com/user-attachments/assets/1021a76e-bcfe-45cf-9276-4da30bd1b83a" />

<img width="640" height="397" alt="Image" src="https://github.com/user-attachments/assets/2c8915db-f0bf-4061-aecf-6c339c55b6b1" />

**Comment by Valdex** [comment]
The same problem here, on a Macbook Pro, the borders glow, and it looks very annoying if the wallpaper is dark, or if you're playing a dark game

**Comment by alexlyee** [comment]
testing this issue on two different macbook pros, one is M4 26.1 and **doesn't have the problem**, and another is an M2 and it has the problem on 26.0.1 and 26.1 (after upgrading).

**Comment by svobs** [comment]
I've been following this issue based on a web search - there was a similar problem in the IINA project's "legacy" full screen mode. We resolved it by ensuring `window.hasShadow = false` when in full screen. Hope this helps.

**Comment by andygrundman** [comment]
I do see this when using Fullscreen, but no one should be using the Fullscreen option. The Borderless option is the correct one to use and doesn't have this problem. M1 Pro MBP and M4 Mini with external display are both fine with borderless.

**Comment by alexlyee** [comment]
resolved this for myself by using the native higher resolution. I was (and still) having this problem on the M2 mac only when using 1080p

**Comment by abedef** [comment]
Hmm, my screenshots use my Mac's native resolution – 3456x2234. Which resolution are you running at?

**Comment by Valdex** [comment]
The problem was solved by itself

**Comment by alexlyee** [comment]
@abedef I still experience this problem on the M2 pro here when I use any other resolution except for 2560 x 1600, which happens to be the native resolution of both the 13" M2 pro here and the display of the computer I'm connecting to

**Comment by abedef** [comment]
Interesting 🤔
I'll try out some other resolutions and see if it makes any difference

**Comment by DeNo64** [comment]
Using changing from Fullscreen to Borderless Fullscreen resolved this for me

**Comment by abedef** [comment]
I can confirm in my case that swapping between borderless and full screen does not affect the border. I did notice, however, that using 4K instead of my screen's native resolution of 3456x2234 makes the borders disappear.

When using a non-native resolution, the moonlight window takes up its own space (one that I can swipe to separately) instead of appearing on top of my main space – possibly related?

**Comment by andygrundman** [comment]
> I can confirm in my case that swapping between borderless and full screen does not affect the border. I did notice, however, that using 4K instead of my screen's native resolution of 3456x2234 makes the borders disappear.
> 
> When using a non-native resolution, the moonlight window takes up its own space (one that I can swipe to separately) instead of appearing on top of my main space – possibly related?

Aha, maybe you have found a bug with the borderless window setting. Indeed if you select Native resolution it will behave like the Fullscreen option instead of Borderless. I always stream at 1440p120 when using my Mac so I never noticed this. Fullscreen is just terrible, no space you can swipe to/from, stats get cut off in the screen corner, I kinda wonder why it's even an option.

**Comment by martinn000** [comment]
I still have this issue, I am on a 2021 M1 Pro 14 inch on 26.0. The only way to not have the border seems to be to have a non-native resolution, at least for me. I would love if someone could fix this as this is driving me crazy. It is there in fullscreen and borderless windowed for me, but as @andygrundman said this may be due to native acting like fullscreen on the borderless option if your resolution is set to native. I do want to note that my moonlight window is in its own space on any option that I choose (other than windowed) regardless of my resolution, and I swipe with 3 fingers to access it (or use mission control).

**Comment by martinn000** [comment]
Following up to add that I updated to the latest MacOS, 26.3, and it is still there.

**Comment by andygrundman** [comment]
Another workaround for this issue is to launch Moonlight with this environment variable. This removes the border if you want to use native resolution, but I don't know if it's still considered buggy or not. 

```
I_WANT_BUGGY_FULLSCREEN=1 /Applications/Moonlight.app/Contents/MacOS/Moonlight
```

Default behavior (BUGGY=0): uses `SDL_WINDOW_FULLSCREEN_DESKTOP` and sets `SDL_HINT_VIDEO_MAC_FULLSCREEN_SPACES` if the resolution is not native.
BUGGY=1 uses `SDL_WINDOW_FULLSCREEN` and never sets the Spaces hint.

**Comment by cgutman** [comment]
Can you try the latest nightly build and see if the issue still exists? We're using SDL3 now instead of SDL2.

**Comment by martinn000** [comment]
> Can you try the latest nightly build and see if the issue still exists? We're using SDL3 now instead of SDL2.

I am on latest nightly with the issue; also to confirm for issue history, buggy=1 does not seem to get rid of the border

EDIT: Clarifying that it does get rid of the border in borderless mode but the window has margins, the same as if you start streaming in "Windowed" and maximize the window

**Comment by cgutman** [comment]
Big kudos to @svobs for the hint about `hasShadow`. That turned out to be the issue, and I've upstreamed the fix for SDL 3.4.2 to fix all SDL-based apps. Once SDL 3.4.2 is released, I'll update our prebuilt version of SDL and that will fix the issue for Moonlight.

**Comment by maoawa** [comment]
this issue still exists in the latest release version and we're waiting for v6.2 to be released. for anyone who'd like to get this solved right now, you may refer to nightly builds: [https://nightly.link/moonlight-stream/moonlight-qt/workflows/build/master](https://nightly.link/moonlight-stream/moonlight-qt/workflows/build/master)
