### ISSUE TITLE
moonlight 3.1.1 don't run on SteamLink with beta 803

### ISSUE THREAD

**Issue by BA-Baracus-BBB** [moonlight-stream/moonlight-qt#566]
moonlight 3.1.1 don't start on SteamLink with beta 803.
The screen goes black and than the SteamLink-UI comes back.

Changes in SteamLink beta 803:
- Added SSL support to the Qt network manager

In beta 802,  I've had no problems with moonlight.

**Comment by cgutman** [comment]
This was a bug in Steam Link firmware 803. It was fixed in 806.

**Comment by tristan-k** [comment]
I'm on build 815 (public) and this still happens. Here's a dmesg output:

```
[  310.482632] memory_engine_release_by_taskid,969 memory note for pid(1691) exceed 64
[  310.483189] [Galois][pe_agent_driver] close file:c9cae200 pid:1691 handle:88de3103
[  310.483345] memory_engine_lookup_shm_node Error alignaddr[1436e9c0]
[  310.483372] memory_engine_lookup_shm_node Error alignaddr[143729c0]
[  310.483426] memory_engine_lookup_shm_node Error alignaddr[14afa2c0]
[  310.483437] memory_engine_lookup_shm_node Error alignaddr[14afe2c0]
[  310.484336] memory_engine_lookup_shm_node Error alignaddr[14b00940]
[  310.484407] memory_engine_lookup_shm_node Error alignaddr[14b01140]
[  310.484416] memory_engine_lookup_shm_node Error alignaddr[14b02a00]
[  310.484422] memory_engine_lookup_shm_node Error alignaddr[14b01940]
[  310.484428] memory_engine_lookup_shm_node Error alignaddr[14b03d80]
[  310.484434] memory_engine_lookup_shm_node Error alignaddr[14372ac0]
[  310.484440] memory_engine_lookup_shm_node Error alignaddr[14b02920]
[  310.484446] memory_engine_lookup_shm_node Error alignaddr[14732ac0]
[  310.484452] memory_engine_lookup_shm_node Error alignaddr[14b04460]
[  310.484458] memory_engine_lookup_shm_node Error alignaddr[157d8dc0]
[  310.484464] memory_engine_lookup_shm_node Error alignaddr[147366c0]
[  310.484470] memory_engine_lookup_shm_node Error alignaddr[14af66c0]
[  310.484475] memory_engine_lookup_shm_node Error alignaddr[1576b7c0]
[  310.484481] memory_engine_lookup_shm_node Error alignaddr[15898dc0]
[  310.484487] memory_engine_lookup_shm_node Error alignaddr[1598abc0]
[  310.484493] memory_engine_lookup_shm_node Error alignaddr[14b0fa00]
[  310.484498] memory_engine_lookup_shm_node Error alignaddr[15aaabc0]
[  310.484504] memory_engine_lookup_shm_node Error alignaddr[14b066c0]
[  310.484509] memory_engine_lookup_shm_node Error alignaddr[15af2bc0]
[  310.484515] memory_engine_lookup_shm_node Error alignaddr[14b0a6c0]
[  310.484520] memory_engine_lookup_shm_node Error alignaddr[14b02280]
[  310.484526] memory_engine_lookup_shm_node Error alignaddr[14b0a7c0]
[  310.484579] memory_engine_lookup_shm_node Error alignaddr[14b02e40]
[  310.484586] memory_engine_lookup_shm_node Error alignaddr[14b0e7c0]
[  310.484591] memory_engine_lookup_shm_node Error alignaddr[14b019e0]
[  310.484597] memory_engine_lookup_shm_node Error alignaddr[14b0e8c0]
[  310.484603] memory_engine_lookup_shm_node Error alignaddr[14b01a40]
[  310.484609] memory_engine_lookup_shm_node Error alignaddr[14afe3c0]
[  310.484615] memory_engine_lookup_shm_node Error alignaddr[14b01aa0]
[  310.484621] memory_engine_lookup_shm_node Error alignaddr[14b01b00]
[  310.484627] memory_engine_lookup_shm_node Error alignaddr[14b29f40]
[  310.484632] memory_engine_lookup_shm_node Error alignaddr[14ca3c40]
[  310.484638] memory_engine_lookup_shm_node Error alignaddr[14afe400]
[  310.484644] memory_engine_lookup_shm_node Error alignaddr[14b021c0]
[  310.484649] memory_engine_lookup_shm_node Error alignaddr[14e83c40]
[  310.484655] memory_engine_lookup_shm_node Error alignaddr[14b03720]
[  310.484660] memory_engine_lookup_shm_node Error alignaddr[14ecec40]
[  310.484666] memory_engine_lookup_shm_node Error alignaddr[14b01b60]
[  310.484671] memory_engine_lookup_shm_node Error alignaddr[14b00200]
[  310.484677] memory_engine_lookup_shm_node Error alignaddr[14b040c0]
[  310.484682] memory_engine_lookup_shm_node Error alignaddr[14b00700]
[  310.484688] memory_engine_lookup_shm_node Error alignaddr[14b03a60]
[  310.484693] memory_engine_lookup_shm_node Error alignaddr[14b00760]
[  310.484699] memory_engine_lookup_shm_node Error alignaddr[14b01d40]
[  310.484706] memory_engine_lookup_shm_node Error alignaddr[14b007c0]
[  310.484711] memory_engine_lookup_shm_node Error alignaddr[14b02880]
[  310.484717] memory_engine_lookup_shm_node Error alignaddr[14b00820]
[  310.484723] memory_engine_lookup_shm_node Error alignaddr[14b029a0]
[  310.484728] memory_engine_lookup_shm_node Error alignaddr[14b00880]
[  310.484734] memory_engine_lookup_shm_node Error alignaddr[14b13940]
[  310.484802] memory_engine_lookup_shm_node Error alignaddr[14b05ac0]
[  310.484810] memory_engine_lookup_shm_node Error alignaddr[14b03b20]
[  310.484817] memory_engine_lookup_shm_node Error alignaddr[14f1ec40]
[  310.484823] memory_engine_lookup_shm_node Error alignaddr[14b047a0]
[  310.484848] memory_engine_lookup_shm_node Error alignaddr[14b18cc0]
[  310.484854] memory_engine_lookup_shm_node Error alignaddr[14b059c0]
[  310.484860] memory_engine_lookup_shm_node Error alignaddr[1571ec40]
[  310.484866] memory_engine_lookup_shm_node Error alignaddr[1572ec40]
[  310.637890] [Galois][pe_agent_driver] open filp:c9d58b80 tgid:1775
[  310.637910] [Galois][pe_agent_driver] filp:c9d58b80 ioctl:set token:80000055 tgid:1775
[  310.638104] [Galois][pe_agent_driver] filp:ccf94600 ioctl:set pe inst:88de3103 tgid:1775 token:80000055
```

**Comment by cgutman** [comment]
@tristan-k please open a new bug for this. Your issue is not the same as this one, since your crash is happening during pairing.
