### ISSUE TITLE
Mouse cursor has wrong position when changing cursor

### ISSUE THREAD

**Issue by makedir** [moonlight-stream/moonlight-qt#674]
Not sure since when this happened, I am somehow sure it worked before. But I noticed, that when the mouse cursor changes to an edit cursor. You can see it here:

Original screen:
![image](https://user-images.githubusercontent.com/6721083/141663394-5cf4a759-f54d-4f86-8d47-6a41350d135c.png)

Moonlight client screen:
![image](https://user-images.githubusercontent.com/6721083/141663396-93d024c2-6ddf-4264-947c-1f113e073b9a.png)

You can reproduce this by opening a notepad on the server and then look at the cursor on the client/server, when hovering over text in notepad, or wordpad, word ect. Leaving the window and reentering it then also bugs it out randomly even more and the x aches is also sometimes broken.

This also happens when you hover the cursor over the border of windows, and then it also has wrong x/y coordinates.

**Comment by cgutman** [comment]
Duplicate of https://github.com/moonlight-stream/nvidia-gamestream-issues/issues/10

**Comment by makedir** [comment]
@cgutman Do you have contacts at Nvidia? Maybe giving them a nice remember of this issue. Ive looked into the other ticket, and the "we are aware of this issue" post is 9 months old and still no fix.

**Comment by cgutman** [comment]
No, I don't. I find out about any updates or changes in new GFE version and drivers at the same time as everyone else.

**Comment by NickoLopez** [comment]
I don't have the issue anymore, has it been fixed in the latest drivers?

**Comment by makedir** [comment]
The wrong x,y coordinates issue seems to be fixed indeed with the last GFE update. Yet the false mouse cursor size is still not fixed.
