### ISSUE TITLE
AirPods (Bluetooth) Audio Bug

### ISSUE THREAD

**Issue by vJan00** [moonlight-stream/moonlight-qt#694]
**Describe the bug**
(1) If you are using AirPods for Audio and get into a discord call or anything that puts the AirPods into "two way mode" (when the microphone is used) before you launch Moonlight, there is no sound.
But if you start Moonlight before you get in a call or anything it works flawlessly.
(2) Also Moonlight crashes if you start Moonlight while in a Discord call, then disconnect from the call (to regain sound) while you try to reconnect to the Moonlight Host.
Second may be related to #560.

**Steps to reproduce**
(1) Connect your AirPods with your Mac, start a Discord-Call before you start Moonlight.
(2) Be in a Discord-Call with your AirPods, while Moonlight is running without Sound. Disconnect from the Discord Call (the AirPods will automatically switch off the microphone) while reconnecting to the Moonlight Host. It will crash.

**Moonlight settings (please complete the following information)**
My audio-settings are set to Stereo - maybe that's why Moonlight is struggling with it because I think that the AirPods get into mono-mode when the Microphone is used. Also the host speakers are muted while streaming but the stream isn't muted while the Moonlight client isn't active.

**Client PC details (please complete the following information)**
 - OS: macOS Monterey (12.1 (21C52))
 - Moonlight Version: v3.1.4
 - GPU: Intel Iris Plus Graphics 655 (1536 MB)

**Server PC details (please complete the following information)**
 - OS: Windows 11 Pro 21H2
 - GeForce Experience version: 3.24.0.126
 - Nvidia GPU driver: 497.09
 - Antivirus and firewall software: Only Windows default

**Moonlight Logs**
(1) [Moonlight-1640259064.log](https://github.com/moonlight-stream/moonlight-qt/files/7769038/Moonlight-1640259064.log)
(2) [Moonlight-1640259849.log](https://github.com/moonlight-stream/moonlight-qt/files/7769118/Moonlight-1640259849.log)

**Comment by patrickjquinn** [comment]
I'll second this, if you do and AirPod's "hand over" from one device running moonlight to another, moonlight crashes.

**Comment by cgutman** [comment]
This was a bug in SDL should be fixed when we updated that.

Can you still reproduce the issue using a dev build? https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/41948703/job/g2pv8o2qg3kp45i3/artifacts

**Comment by Terane86** [comment]
I'm also having this same exact issue on both my MacBook Pro and iPad Pro 5th Gen.

What can I provide to help out?

**Comment by cgutman** [comment]
The bug is already fixed. We just need someone to confirm that it's fixed using a dev build like this: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/42215360/job/foiu4108u0biod33/artifacts

**Comment by Terane86** [comment]
Currently from what I've tested on my MacBook, yes, it's working.  I can report back if it acts up still.

**Comment by Terane86** [comment]
I was just following up on this.  My MacBook is still working just fine but my iPad Pro is still having this issue on iPadOS 15.2.1.  Any updates on that version?

**Comment by cgutman** [comment]
This fix is released in v3.2.0.

> I was just following up on this. My MacBook is still working just fine but my iPad Pro is still having this issue on iPadOS 15.2.1. Any updates on that version?

Please open an issue on the [moonlight-ios](https://github.com/moonlight-stream/moonlight-ios) project if there are issues on iOS. That wouldn't be related to this issue, since they use completely different codebases.
